services:
  forwarder:
    restart: always
    build: ./dnsmasq
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    networks:
      vpcbr:
        ipv4_address: 10.10.0.2
  attacker:
    restart: always
    build: ./attacker
    volumes:
      - ./attacker:/app
    cap_add:
      - NET_ADMIN
    networks:
      vpcbr:
        ipv4_address: 10.10.0.3
    dns:
      - 10.10.0.2
  cache:
    restart: always
    build: ./cache
    volumes:
      - ./cache:/app
    cap_add:
      - NET_ADMIN
    networks:
      vpcbr:
        ipv4_address: 10.10.0.4
  malicious-server:
    restart: always
    build: ./malicious-server
    networks:
      vpcbr:
        ipv4_address: 10.10.0.5
    ports:
      - "8080:80"
  client:
    restart: always
    build: ./client
    networks:
      vpcbr:
        ipv4_address: 10.10.0.6
    dns:
      - 10.10.0.2
    ports:
      - "6080:80"
    environment:
      - VNC_PASSWORD=password
      - USER=root
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: "10.10.0.0/24"
